service: uniswap-v2-api
frameworkVersion: "3"

plugins:
  - serverless-plugin-typescript
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x

functions:
  hello:
    handler: app/handler.hello
    events:
      - httpApi:
          path: /
          method: get
